name: Build Dockerfile and push into ghcr


on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  build:
    name: Build Dockerfile and push into ghcr
    runs-on: ubuntu-latest
    timeout-minutes: 10


    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
