name: Build Dockerfile and push into ghcr

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Dockerfile and push into ghcr
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: downcase REPO
        id: repo
        shell: bash
        run: |
          export FULLNAME="ghcr.io/${{ github.repository }}"
          echo "REPO=${FULLNAME,,}" >> $GITHUB_OUTPUT
          echo "REPO=${FULLNAME,,}"

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.repo.outputs.REPO }}:latest
